apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service.yml
  labels:
    app: order-service.yml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service.yml
  template:
    metadata:
      labels:
        app: order-service.yml
    spec:
      containers:
        - name: order-service.yml
          image: order-service.yml
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9002
          env:
            - name: POLAR_CATALOG_SERVICE_URI
              value: http://catalog-service
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://polar-postgres/polardb_order
            - name: SPRING_FLYWAY_URL
              value: jdbc:postgresql://polar-postgres/polardb_order